{{- if not .Release.Namespace }}
  {{- fail "the value 'namespace' is required" }}
{{- end }}
{{- if .Values.clusterRoleBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rbac.clusterRoleBindingName" . }}
  labels:
  {{- include "rbac.labels" . | nindent 4 }}
roleRef:
  {{- with .Values.clusterRoleBinding.roleRef }}
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ .name }}
  {{- end }}
subjects:
  {{- with .Values.clusterRoleBinding.subjects }}{{- tpl (toYaml . ) $ | nindent 2 }}{{- end }}
  {{- end }}